---
- name: Install packages
  hosts: localhost
  become: yes
  vars:
    common_packages:
      - git
    redhat_packages:
      - bind-utils
    debian_packages:
      - bind9-utils

  tasks:
    - name: Install common packages on all distributions
      ansible.builtin.package:
        name: "{{ common_packages }}"
        state: present

    - name: Install Red Hat-specific packages
      ansible.builtin.yum:
        name: "{{ redhat_packages }}"
        state: present
      when: ansible_facts['os_family'] == 'RedHat'

    - name: Install Debian-specific packages
      ansible.builtin.apt:
        name: "{{ debian_packages }}"
        state: present
        update_cache: yes
      when: ansible_facts['os_family'] == 'Debian'
