---
- name: Install packages
  hosts: localhost
  become: yes
  vars:
    common_packages:
      - git
      - gcc-riscv64-linux-gnu
      - binutils-riscv64-linux-gnu
    redhat_packages:
      - bind-utils
      - qemu-system-x86
    debian_packages:
      - bind9-utils
      - qemu-system-misc
    arch_packages:
      - riscv64-linux-gnu-binutils
      - riscv64-linux-gnu-gcc
      - riscv64-linux-gnu-gdb
      - qemu-emulators-full

  tasks:
    - name: Install common packages on all distributions
      ansible.builtin.package:
        name: "{{ common_packages }}"
        state: present

    - name: Install Red Hat-specific packages
      ansible.builtin.yum:
        name: "{{ redhat_packages }}"
        state: present
      when: ansible_facts['os_family'] == 'RedHat'

    - name: Install Debian-specific packages
      ansible.builtin.apt:
        name: "{{ debian_packages }}"
        state: present
        update_cache: yes
      when: ansible_facts['os_family'] == 'Debian'

    - name: Install Arch-specific packages
      ansible.builtin.pacman:
        name: "{{ arch_packages }}"
        state: present
      when: ansible_facts['os_family'] == 'Archlinux'
