name: Lab Tools

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        #os: [ubuntu-latest, debian-latest, fedora-latest, archlinux-latest]
        os: [ubuntu-latest, fedora-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Ansible
      run: |
        if [[ "${{ matrix.os }}" == *"ubuntu"* || "${{ matrix.os }}" == *"debian"* ]]; then
          sudo apt-get update
          sudo apt-get install -y ansible
        elif [[ "${{ matrix.os }}" == *"fedora"* ]]; then
          sudo dnf install -y ansible
        elif [[ "${{ matrix.os }}" == *"archlinux"* ]]; then
          sudo pacman -Syu --noconfirm ansible
        fi

    - name: Run Ansible playbook
      run: ansible-playbook playbook.yml

    - name: Check qemu-system-riscv64 version
      run: qemu-system-riscv64 --version

    - name: Check riscv64-linux-gnu-gcc version
      run: riscv64-linux-gnu-gcc --version

    - name: Check riscv64-unknown-elf-gcc version
      run: riscv64-unknown-elf-gcc --version

    - name: Check riscv64-unknown-linux-gnu-gcc version
      run: riscv64-unknown-linux-gnu-gcc --version
