name: Lab Tools

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        #os: [ubuntu-latest, debian-latest, fedora-latest, archlinux-latest]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Ansible
      run: |
        if [[ "${{ matrix.os }}" == *"ubuntu"* || "${{ matrix.os }}" == *"debian"* ]]; then
          sudo apt-get update
          sudo apt-get install -y ansible
        elif [[ "${{ matrix.os }}" == *"fedora"* ]]; then
          sudo dnf install -y ansible
        elif [[ "${{ matrix.os }}" == *"archlinux"* ]]; then
          sudo pacman -Syu --noconfirm ansible
        fi

    - name: Run Ansible playbook
      run: ansible-playbook playbook.yml

    - name: Check qemu-system-riscv64 version
      run: qemu-system-riscv64 --version

    - name: Check riscv64 compilers versions
      run: |
        set -e
        riscv64-linux-gnu-gcc --version || true
        riscv64-unknown-elf-gcc --version || true
        riscv64-unknown-linux-gnu-gcc --version || true

    - name: Ensure at least one compiler is available
      run: |
        if ! (riscv64-linux-gnu-gcc --version || riscv64-unknown-elf-gcc --version || riscv64-unknown-linux-gnu-gcc --version); then
          echo "None of the RISC-V compilers are available" >&2
          exit 1
        fi

    - name: Clone xv6-labs-2024 repository
      run: git clone --depth 1 git://g.csail.mit.edu/xv6-labs-2024

    - name: Run xv6 with QEMU
      run: |
        cd xv6-labs-2024
        ../scripts/run_qemu.expect
        cat qemu.log
